GET /api/projects
Accept: application/json

{{
    if (response.parsedBody.length && response.parsedBody.length > 0) {
        projectId = response.parsedBody[response.parsedBody.length-1].id;
    }
}}